// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcSgjEuMuJ_weAnDjmwhmKshAe1eGFVcc',
    appId: '1:970558747052:web:b4f6be04a5a5f07234ca09',
    messagingSenderId: '970558747052',
    projectId: 'govhack2024',
    authDomain: 'govhack2024.firebaseapp.com',
    storageBucket: 'govhack2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARcZKBQq1ASegcXZOQBAisffLyKZ89GFU',
    appId: '1:970558747052:android:3e6ca4052bbebffb34ca09',
    messagingSenderId: '970558747052',
    projectId: 'govhack2024',
    storageBucket: 'govhack2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6PS4VC305BZISKash1RvYFJnuqXNylwY',
    appId: '1:970558747052:ios:7507998afbaaa4b234ca09',
    messagingSenderId: '970558747052',
    projectId: 'govhack2024',
    storageBucket: 'govhack2024.appspot.com',
    iosBundleId: 'com.example.govhack2024',
  );
}
