name: govhack2024
description: "A new Flutter project."
version: 0.1.0+1

publish_to: "none"

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flex_color_scheme: ^7.3.1
  flutter_riverpod: ^3.0.0-dev.3
  gap: ^3.0.1
  go_router: ^14.2.7
  riverpod_annotation: ^3.0.0-dev.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  custom_lint: ^0.5.11
  flutter_lints: ^4.0.0
  go_router_builder: ^2.7.1
  icons_launcher: ^2.1.7
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  flutter_gen_runner: ^5.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_high.png

flutter_gen:
  generate: true
  output: lib/generated/
  line_length: 100

  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
      style: dot-delimiter

  fonts:
    enabled: false

icons_launcher:
  image_path: "assets/logo/logo_high.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#000000"
      adaptive_foreground_image: "assets/logo/logo_high.png"
      # adaptive_round_image: "assets/icon/icon_android_round.png"
      # adaptive_monochrome_image: "assets/icon/icon_android_mono.png"
    ios:
      enable: true
    linux:
      enable: false
    macos:
      enable: false
    web:
      enable: true
    windows:
      enable: false
